### PR TITLE
Added German Translation for Unraid-Docs

### PR DESCRIPTION
**Pull request by Kippenhof**

### CODE REVIEW

**Comment by Kippenhof** [comment]
1. draft

**Review by andrewstech — CHANGES_REQUESTED** [review]
Change `[hier](https://alpha-video.andrewstech.me/docs/doc4)`

To

`[hier](doc4.md)`

This makes the links go to the current language.

**Comment by Kippenhof** [comment]
> Change `[hier](https://alpha-video.andrewstech.me/docs/doc4)`
> 
> To
> 
> `[hier](docs.md)`
> 
> This makes the links go to the current language.

sounds smart. i didn't know the folder structure of the back-end

**Comment by Kippenhof** [comment]
@andrewstech How can i mark an Change Request as done?

**Comment by andrewstech** [comment]
> @andrewstech How can i mark an Change Request as done?

Normally request a review and when it gets approved it would auto merge. As you have privileges you can add the label ready and github will approve it for you.

**Review by andrewstech — APPROVED** [review]
Good work :)

**Pull request merged**
