### PR TITLE
Fix Python-Logo stretching

### PR DESCRIPTION
**Pull request by Kippenhof**

### CODE REVIEW

**Comment by Kippenhof** [comment]
@andrewstech do you know why no Deployment-Preview is generated?

**Comment by andrewstech** [comment]
> @andrewstech do you know why no Deployment-Preview is generated?

Its appearing for me. It's the last check. Click the last details button.
Screenshot_20210531-062015_Chrome

**Comment by andrewstech** [comment]
https://deploy-preview-42--alpha-video-docs.netlify.app/

**Comment by Kippenhof** [comment]
> > @andrewstech do you know why no Deployment-Preview is generated?
> 
> Its appearing for me. It's the last check. Click the last details button.
> Screenshot_20210531-062015_Chrome

oh sorry, xD Yes, i also can see it

**Comment by Kippenhof** [comment]
It should be fixed, there was just an css Variable missing, maybe have a last look at it

[New](https://deploy-preview-42--alpha-video-docs.netlify.app/) [Old](https://alpha-video.andrewstech.me)

**Review by andrewstech — APPROVED** [review]
Looks Great. Thanks for help. :)

**Pull request merged**
